export const SAGA_FETCH_RANDOM_FACT = 'SAGA_FETCH_RANDOM_FACT'
export const FETCH_RANDOM_FACT = 'FETCH_RANDOM_FACT'

export const SAGA_FETCH_CATEGORIES_FACTS = 'SAGA_FETCH_CATEGORIES_FACTS'
export const FETCH_CATEGORIES_FACTS = 'SAGA_FETCH_CATEGORIES_FACTS'

export const APP_LOAD_FACT = 'APP_LOAD_FACT'
export const APP_NOT_LOAD_FACT = 'APP_NOT_LOAD_FACT'